<?php
/**
 * MMBN5 Tileset Splitter
 * 
 * This script will read a combined tileset file, previously generated by
 * PixelPet, and split it in two individual tileset files, which is the
 * expected format to be inserted in-game.
 * 
 * The split logic works by receiving an offset (e.g. 0283e8), then loading
 * the combined tileset file with name like "td-0283e8.bin", and split it in
 * two files: "td-0283e8-0.bin" and "td-0283e8-1.bin", using as a split point
 * the data from the "splt-0283e8.bin" file.
 * 
 * Usage: php split_tileset.php <offset> <version_suffix>
 * 
 * Arguments:
 * - offset: The offset used to identify the combined tileset.
 * - version_suffix: (optional) Suffix to identify the game version,
 *   e.g. "tc" or "tp".
 */

require_once 'common.php';

// Reading parameters from the command line.
if ($argc < 1) {
    echo "Usage: php split_tileset.php <offset> <version_suffix>\n";
    exit(1);
}

$offset = $argv[1];
$version_suffix = isset($argv[2]) ? "-{$argv[2]}" : '';

$combined_tileset_filename = "data/td-{$offset}{$version_suffix}.bin";
if (!file_exists($combined_tileset_filename)) {
    echo "Error: Combined tileset file does not exist.\n";
    exit(1);
}

$split_point_tile_filename = "data/splt-{$offset}{$version_suffix}.bin";
if (!file_exists($split_point_tile_filename)) {
    echo "Error: Split point tilemap file is required.\n";
    echo "Please generate a file at \"$split_point_tile_filename\" with a single ";
    echo "8bpp tile file (64 bytes), which will be used to split the tileset.\n";
    exit(1);
}

$combined_tileset_file = fopen($combined_tileset_filename, 'rb');
$split_point_tile_file = fopen($split_point_tile_filename, 'rb');

// Getting the split point tile data.
$split_point_tile_data = fread($split_point_tile_file, 0x40);
fclose($split_point_tile_file);

// Check where, in the combined file, is the split point tile.
$split_offset = 0;
while (!feof($combined_tileset_file)) {
    $tile_data = fread($combined_tileset_file, 0x40);
    if ($tile_data === false || strlen($tile_data) < 0x40) {
        break;
    }
    if ($tile_data === $split_point_tile_data) {
        $split_offset = ftell($combined_tileset_file) - 0x40;
        break;
    }
}

echo 'Split offset: 0x' . dechex($split_offset) . "\n";
fseek($combined_tileset_file, 0, SEEK_SET);

$first_splitted_tileset = "data/td-{$offset}{$version_suffix}-0.bin";
$second_splitted_tileset = "data/td-{$offset}{$version_suffix}-1.bin";
$f1 = fopen($first_splitted_tileset, 'wb');
$f2 = fopen($second_splitted_tileset, 'wb');
if ($f1 === false || $f2 === false) {
    echo "Error: Couldn't create the splitted tileset files.\n";
    exit(1);
}

// Writing first splitted tileset file.
$data = fread($combined_tileset_file, $split_offset);
fwrite($f1, $data);

// Writing second splitted tileset file.
fseek($combined_tileset_file, $split_offset, SEEK_SET);
while (!feof($combined_tileset_file)) {
    $data = fread($combined_tileset_file, 8192);
    if ($data === false) break;
    if (strlen($data) > 0) {
        fwrite($f2, $data);
    }
}

// Closing files.
fclose($combined_tileset_file);
fclose($f1);
fclose($f2);

$out1 = basename($first_splitted_tileset);
$out2 = basename($second_splitted_tileset);
$size1 = filesize($first_splitted_tileset);
$size2 = filesize($second_splitted_tileset);
echo "Generated files:\n";
echo " - {$out1} ({$size1} bytes)\n";
echo " - {$out2} ({$size2} bytes)\n";